version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      sveltekit:
        patterns:
          - '@sveltejs/*'
          - 'svelte'
          - 'svelte-*'
          - 'vite'
          - 'vitest'
          - '@vitest/*'
          - 'vitest-*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      cloudflare:
        patterns:
          - 'wrangler'
      lint-and-format:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'prettier'
          - 'prettier-*'
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions:
        patterns:
          - '*'
